### ISSUE TITLE
Training fails when scheduled among other previous protocols scheduled

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-cryodrgn#35]
Training fails to create the output due to this code:

https://github.com/scipion-em/scipion-em-cryodrgn/blob/master/cryodrgn/protocols/protocol_base.py#L234

This line, implies that the "previous to previous" protocol has to have an output. If this protocol was scheduled at the same time....the "training-shceduling process" cannot know that  "previous to previous" has to be updated.

A possible fix would be to have in the CryoDRGN particles set a pointer to the set of particles (indirect pointer better, with extended).

**Comment by azazellochg** [comment]
@pconesa can you check with devel again? I dont have streaming things...

**Comment by pconesa** [comment]
Sure.... it is more related to Scheduling. Here is a hint to test this case:

1.- Run the test
2.- Reset the test project
3.- make the training "wait for" an non dependent preprocessing (or something that will delay it enough so when the first wait of the scheduling is consumed...
4.- Schedule the workflow.

**Comment by azazellochg** [comment]
Awesome,will test this tomorrow

**Comment by azazellochg** [comment]
Seems working for me:
```
00001:   Scheduling protocol 237, PID: 51370,prerequisites: [96], works in streaming: False.
00002:   Waiting 60 seconds before start checking inputs 
00003:   Checking input data...
00004:   Updated protocol: 190 (preprocess scale=64)
00005:   CryoDrgnParticles (65 x 65, 5.53 Å/px) is not blocking this protocol. All ready.
00006:   Updated protocol: 2 (pwem - import particles)
00007:   Checking prerequisites... [96]
00008:   The protocol 96 (preprocess scale=64) is up to date
00009:   Launching the protocol >>>>
```
